apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: murgdur
spec:
  selector:
    matchLabels:
      observability: prometheus
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
