apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: murgdur-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: murgdur-secrets
  dataFrom:
    - extract:
        key: prod/murgdur/app
